package com.viwe.task_management_system.controller;

import com.viwe.task_management_system.config.JwtProperties;
import com.viwe.task_management_system.config.SecurityConfig;
import com.viwe.task_management_system.dto.response.AuthResponse;
import com.viwe.task_management_system.entity.User;
import com.viwe.task_management_system.enums.Role;
import com.viwe.task_management_system.exception.GlobalExceptionHandler;
import com.viwe.task_management_system.security.JwtAuthenticationEntryPoint;
import com.viwe.task_management_system.service.AuthService;
import com.viwe.task_management_system.service.JwtService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.time.Instant;
import java.util.Base64;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.BDDMockito.given;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Endpoint-level JWT security tests exercising the full Spring Security
 * filter chain via {@code @WebMvcTest}.
 *
 * <p>Unlike {@link com.viwe.task_management_system.service.JwtServiceTest},
 * which tests token logic in isolation, this class tests the HTTP surface:
 *
 * <ul>
 *   <li><b>Protected endpoint without a token</b> → 401 UNAUTHORIZED</li>
 *   <li><b>Protected endpoint with an invalid/tampered token</b> → 401</li>
 *   <li><b>Protected endpoint with an expired token</b> → 401</li>
 *   <li><b>Protected endpoint with a valid token</b> → request passes the filter (no 401)</li>
 *   <li><b>Public endpoint without a token</b> → permitted (no 401)</li>
 * </ul>
 *
 * <h2>Design</h2>
 * <p>The real {@link com.viwe.task_management_system.security.JwtAuthenticationFilter},
 * {@link JwtAuthenticationEntryPoint}, and {@link JwtService} are wired via a
 * {@link TestSecurityConfig} inner configuration, so the filter chain behaves
 * identically to production. Only {@link UserDetailsService} and {@link AuthService}
 * are mocked because they require a database.
 *
 * <p>Tokens are generated by a local {@link JwtService} instance that shares
 * the same {@link JwtProperties} bean supplied to the Spring context.
 *
 * <p>{@link AuthController} is the controller under test. Its public endpoints
 * ({@code /api/auth/login}, {@code /api/auth/register}) test the "no token
 * needed" path. Requests to {@code /api/tasks/**} (not handled by
 * {@code AuthController}) test the filter rejection paths — a valid token
 * results in authentication succeeding, after which routing finds no handler
 * and returns 404, whereas an invalid/missing token returns 401 before routing.
 */
@WebMvcTest(controllers = AuthController.class)
@Import({GlobalExceptionHandler.class, SecurityConfig.class,
         JwtSecurityIntegrationTest.TestSecurityConfig.class})
@DisplayName("JWT Security — endpoint-level")
class JwtSecurityIntegrationTest {

    // ── Inner test configuration ──────────────────────────────────────────────

    /**
     * Provides the real {@link JwtService} and a test-specific
     * {@link JwtProperties} so no environment variables are needed.
     *
     * <p>The 32-byte (256-bit) Base64-encoded key meets the minimum enforced
     * by {@link JwtService}'s constructor guard.
     */
    @TestConfiguration
    static class TestSecurityConfig {

        static final String TEST_SECRET =
                Base64.getEncoder().encodeToString(
                        "TestSecret1234567890TestSecret12".getBytes());

        @Bean
        JwtProperties testJwtProperties() {
            JwtProperties props = new JwtProperties();
            props.setSecret(TEST_SECRET);
            props.setExpirationMs(3_600_000L);
            return props;
        }

        @Bean
        JwtService testJwtService(JwtProperties jwtProperties) {
            return new JwtService(jwtProperties);
        }

        @Bean
        JwtAuthenticationEntryPoint testJwtAuthenticationEntryPoint() {
            return new JwtAuthenticationEntryPoint();
        }
    }

    // ── Mocked beans (require DB or external state) ───────────────────────────

    @MockitoBean
    private AuthService authService;

    @MockitoBean
    private UserDetailsService userDetailsService;

    // ── Fields ────────────────────────────────────────────────────────────────

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JwtService jwtService;

    private User testUser;

    @BeforeEach
    void setUp() {
        testUser = User.builder()
                .id(1L)
                .firstName("Alice")
                .lastName("Smith")
                .email("alice@example.com")
                .password("hashed")
                .role(Role.USER)
                .build();

        // The JWT filter calls loadUserByUsername(email) on every request that
        // carries a Bearer token. Return our test user so validation can proceed.
        given(userDetailsService.loadUserByUsername("alice@example.com"))
                .willReturn(testUser);
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Public endpoint — no token required
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Public endpoint — no token required")
    class PublicEndpoint {

        @Test
        @DisplayName("POST /api/auth/login without a token is allowed through (public endpoint)")
        void login_noToken_allowedThrough() throws Exception {
            given(authService.login(any()))
                    .willReturn(AuthResponse.of("some.jwt.token"));

            mockMvc.perform(post("/api/auth/login")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"email\":\"alice@example.com\",\"password\":\"pass\"}"))
                    .andExpect(status().isOk());
        }

        @Test
        @DisplayName("POST /api/auth/register without a token returns 201 (public endpoint)")
        void register_noToken_allowedThrough() throws Exception {
            given(authService.register(any()))
                    .willReturn(AuthResponse.of("some.jwt.token"));

            mockMvc.perform(post("/api/auth/register")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"firstName\":\"Alice\",\"lastName\":\"Smith\","
                                    + "\"email\":\"alice@example.com\",\"password\":\"password1\"}"))
                    .andExpect(status().isCreated());
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Protected endpoint — no token
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Protected endpoint — no token")
    class ProtectedEndpointNoToken {

        @Test
        @DisplayName("GET /api/tasks without Authorization header returns 401")
        void protectedEndpoint_noToken_returns401() throws Exception {
            mockMvc.perform(get("/api/tasks"))
                    .andExpect(status().isUnauthorized());
        }

        @Test
        @DisplayName("GET /api/tasks without a token returns UNAUTHORIZED error code in body")
        void protectedEndpoint_noToken_returns401ErrorBody() throws Exception {
            mockMvc.perform(get("/api/tasks"))
                    .andExpect(status().isUnauthorized())
                    .andExpect(jsonPath("$.status").value(401))
                    .andExpect(jsonPath("$.error").value("UNAUTHORIZED"));
        }

        @Test
        @DisplayName("DELETE /api/tasks/1 without a token returns 401")
        void protectedDeleteEndpoint_noToken_returns401() throws Exception {
            mockMvc.perform(delete("/api/tasks/1"))
                    .andExpect(status().isUnauthorized());
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Protected endpoint — valid token
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Protected endpoint — valid token")
    class ProtectedEndpointValidToken {

        @Test
        @DisplayName("GET /api/tasks with a valid Bearer token is not rejected with 401")
        void protectedEndpoint_validToken_filterAcceptsToken() throws Exception {
            String token = jwtService.generateToken(testUser);

            // /api/tasks is not handled by AuthController. After the filter accepts
            // the valid token, routing cannot find a handler. This produces either
            // 404 (no handler found) or 500 (DispatcherServlet error path) depending
            // on the @WebMvcTest slice's error handling — but critically NOT 401.
            // Receiving anything other than 401 proves the token was accepted.
            int status = mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Bearer " + token))
                    .andReturn()
                    .getResponse()
                    .getStatus();

            org.assertj.core.api.Assertions.assertThat(status)
                    .as("Valid token must NOT produce 401 — got HTTP " + status)
                    .isNotEqualTo(401);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Protected endpoint — invalid / tampered token
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Protected endpoint — invalid token")
    class ProtectedEndpointInvalidToken {

        @Test
        @DisplayName("GET /api/tasks with a tampered token returns 401")
        void protectedEndpoint_tamperedToken_returns401() throws Exception {
            String token = jwtService.generateToken(testUser);
            // Alter the last character to invalidate the HMAC signature
            String tampered = token.substring(0, token.length() - 1) + "X";

            mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Bearer " + tampered))
                    .andExpect(status().isUnauthorized())
                    .andExpect(jsonPath("$.status").value(401));
        }

        @Test
        @DisplayName("GET /api/tasks with a garbage token returns 401")
        void protectedEndpoint_garbageToken_returns401() throws Exception {
            mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Bearer not.a.real.jwt"))
                    .andExpect(status().isUnauthorized());
        }

        @Test
        @DisplayName("GET /api/tasks with wrong Authorization scheme returns 401")
        void protectedEndpoint_wrongScheme_returns401() throws Exception {
            String token = jwtService.generateToken(testUser);
            mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Token " + token))
                    .andExpect(status().isUnauthorized());
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Protected endpoint — expired token
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Protected endpoint — expired token")
    class ProtectedEndpointExpiredToken {

        @Test
        @DisplayName("GET /api/tasks with an expired token returns 401")
        void protectedEndpoint_expiredToken_returns401() throws Exception {
            Instant pastExpiry = Instant.now().minusSeconds(1);
            String expiredToken = jwtService.generateToken(testUser, pastExpiry);

            mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Bearer " + expiredToken))
                    .andExpect(status().isUnauthorized())
                    .andExpect(jsonPath("$.status").value(401))
                    .andExpect(jsonPath("$.error").value("UNAUTHORIZED"));
        }

        @Test
        @DisplayName("GET /api/tasks with a token expired 1 hour ago returns 401")
        void protectedEndpoint_longExpiredToken_returns401() throws Exception {
            Instant oneHourAgo = Instant.now().minusSeconds(3_600);
            String expiredToken = jwtService.generateToken(testUser, oneHourAgo);

            mockMvc.perform(get("/api/tasks")
                            .header("Authorization", "Bearer " + expiredToken))
                    .andExpect(status().isUnauthorized());
        }
    }
}
